FinalProjectKiwiFeeds/project_kiwifeeds/app_food/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path("<int:restaurant_id>/add-food/", FoodCreateView.as_view(),name="add-food"),
    #TODO: View Food List View Does Not Exist
    path("", FoodList, name="view-food"),
    path('<int:food_id>/edit-food/', FoodUpdateView.as_view(), name='edit-food'),
    # path("<int:food_id>/edit-food", EditFood,name="edit-food"),
    path("<int:food_id>/delete-food", DeleteFood, name="delete-food"),
]

FinalProjectKiwiFeeds/project_kiwifeeds/app_restaurants/urls.py
from django.urls import path
from .views import restaurant_list, restaurant_details, RestaurantCreateView, RestaurantEditView, RestaurantDeleteView

urlpatterns = [
   path("", restaurant_list, name="restaurant-list"),
   path("<int:restaurant_id>/", restaurant_details, name="restaurant-details"),
   path("create/", RestaurantCreateView, name="create-restaurant"),
   path("<int:restaurant_id>/edit/", RestaurantEditView, name="edit-restaurant"),
   path("<int:restaurant_id>/delete/", RestaurantDeleteView, name="delete-restaurant"),

]

FinalProjectKiwiFeeds/project_kiwifeeds/project_kiwifeeds/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', views.HomeView.as_view() , name='home-page'),
    path('signup-login', views.login_or_signup),
    path('privacy-policy', views.privacy_policy),
    path("restaurants/", include("app_restaurants.urls")),
    path('user/', include('app_user.urls') ),
    path('reviews/', include('app_reviews.urls') , name='reviews'),
    path('food/', include('app_food.urls'), name='food'),
    path('favorites-restaurants/', include('app_favorites.urls',)),


    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FinalProjectKiwiFeeds/project_kiwifeeds/app_food/models.py
from django.db import models
import os
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
def get_food_image_upload_path(instance, filename):
    # Get the restaurant ID and image number
    # restaurant_id = instance.restaurant.id

    # Construct the upload path: 'Restaurant/restaurant_id/food_image/food_id.jpg'
    return os.path.join('restaurant', 'food_image', filename)

class Food(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=300)
    food_price = models.DecimalField(max_digits=5, decimal_places=2)
    restaurant = models.ForeignKey('app_restaurants.Restaurant', on_delete=models.PROTECT,related_name='food')
    food_picture = models.ImageField(
        # default='/profile_pics/temp_pfp_placeholder_REPLACE_LATER.avif',
        upload_to=get_food_image_upload_path,
        height_field=None,
        width_field=None
    )
  

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
      return reverse('food', kwargs={'pk': self.pk})

FinalProjectKiwiFeeds/project_kiwifeeds/app_restaurants/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Restaurant(models.Model):
    restaurant_name = models.CharField(max_length=255)
    restaurant_description = models.CharField(max_length=255)
    restaurant_location = models.CharField(max_length=255)
    # Restaurant Owner is one-to-one relationship with userProfile
    restaurant_owner = models.ForeignKey('app_user.UserProfile',on_delete=models.PROTECT, related_name='restaurant_owner_user',null=True,blank=True)
    def __str__(self):
        return f'{self.restaurant_name}, owned by {self.restaurant_owner}'

FinalProjectKiwiFeeds/project_kiwifeeds/app_restaurants/forms.py
from django.forms import ModelForm
from .models import Restaurant

class RestaurantForm(ModelForm):

    class Meta:
        model = Restaurant
        fields = ["restaurant_name","restaurant_owner","restaurant_description","restaurant_location"]

FinalProjectKiwiFeeds/project_kiwifeeds/app_restaurants/views.py
from django.shortcuts import get_object_or_404 ,render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from app_restaurants.models import Restaurant
from app_restaurants.forms import RestaurantForm
from app_food.forms import FoodForm
from app_favorites.models import Favorites
from app_reviews.models import Review
from django.db.models import Avg

def restaurant_list(request):
    model = Restaurant.objects.all()
    return render(request,'app_restaurants/restaurant_list.html',{"restaurant_list" : model})

def restaurant_details(request, restaurant_id):
    # model = Restaurant.objects.get(pk=restaurant_id)

    # Retrieve the restaurant object or return a 404 error if it doesn't exist
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    # Retrieve the associated reviews for the restaurant
    reviews = restaurant.reviews.all()
     # Calculate the overall rating using Avg
    overall_rating = Review.objects.filter(restaurant=restaurant).aggregate(Avg('rating'))['rating__avg']
    foods=restaurant.food.all()
    # print(reviews)
    # print(foods)
    is_favorite = False

    if request.user.is_authenticated:
        user_profile = request.user.userprofile
        # Check if the restaurant is in the user's favorites
        is_favorite = Favorites.objects.filter(user=user_profile, restaurant=restaurant).exists()
    # print('fav-restaurant')
    # print(is_favorite)
    context = {
        "restaurant": restaurant,
        "reviews": reviews,  # Pass the reviews queryset to the context
         'is_favorite': is_favorite,
         'overall_rating': overall_rating,
         'foods':foods
    }

    return render(request, 'app_restaurants/restaurant_details.html', context)

def RestaurantCreateView(request):
    form=RestaurantForm()
    if request.method == 'POST':
        form = RestaurantForm(request.POST)
        if form.is_valid():
            # Set the restaurant owner field to the currently logged-in user
            form.instance.restaurant_owner = request.user.userprofile  # Assuming user's profile is stored in 'UserProfile' field

            form.save()
            return HttpResponseRedirect("/restaurants/")
    else:
        # If the request method is not POST, create an empty form with the initial owner
        form = RestaurantForm(initial={'restaurant_owner': request.user.userprofile})  # Assuming user's profile is stored in 'UserProfile' field

    return render(request,'app_restaurants/create_restaurant.html', {"form": form})

# def RestaurantEditView(request, restaurant_id):
#     model = Restaurant.objects.get(pk=restaurant_id)
#     form = RestaurantForm()
#     if request.method =='POST':
#         print(request.POST)
#         form = RestaurantForm(request.POST,instance=model)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect("/restaurants/")
#         else:
#             form = RestaurantForm()
#     else:
#         form = RestaurantForm(instance=model)

#     return render(request,'app_restaurants/edit_restaurant.html', {"form": form})


def RestaurantEditView(request, restaurant_id):
    # Retrieve the restaurant instance
    restaurant = Restaurant.objects.get(pk=restaurant_id)
    
    
    if request.method == 'POST':
        # Check if the form for editing restaurant details is submitted
        if 'edit_restaurant_form' in request.POST:
            restaurant_form = RestaurantForm(request.POST, instance=restaurant)
            if restaurant_form.is_valid():
                restaurant_form.save()
                return HttpResponseRedirect(f"/restaurants/{restaurant.id}")

    else:
        # Initialize forms for editing restaurant and adding food items
        restaurant_form = RestaurantForm(instance=restaurant)
        # food_form = FoodForm()
    context={
         "restaurant_form": restaurant_form,
        # "food_form": food_form,
        "restaurant": restaurant,
    }
    return render(request, 'app_restaurants/edit_restaurant.html', context)

def RestaurantDeleteView(request, restaurant_id):
    model = {}
    obj = get_object_or_404(Restaurant, id=restaurant_id)
    if request.method =='POST':
        obj.delete()
        return HttpResponseRedirect(reverse('restaurant-list'))
    return render(request,'app_restaurants/delete_restaurant.html', {})

FinalProjectKiwiFeeds/project_kiwifeeds/templates/app_restaurants/create_restaurant.html
<!-- TODO: Authorization so only user can create if Business Group User -->
{% extends 'base/base.html' %}
{% block content %}
<section>
    {% comment %} <h1>Create New Restaurant</h1>
    <hr>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-action" type="submit"/>Create Restaraunt</button>
    </form> {% endcomment %}
    <h1>Add a New Restaurant</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.restaurant_owner.as_hidden }}
        <div class="form-group">
            <label for="{{ form.restaurant_name.id_for_label }}">Restaurant Name:</label>
            {{ form.restaurant_name }}
        </div>
    
        <div class="form-group">
            <label for="{{ form.restaurant_description.id_for_label }}">Description:</label>
            {{ form.restaurant_description }}
        </div>
    
        <div class="form-group">
            <label for="{{ form.restaurant_location.id_for_label }}">Location:</label>
            {{ form.restaurant_location }}
        </div>
        {% comment %} <div class="form-group">
            <label for="{{ form.restaurant_location.id_for_label }}">Restaurant Owner:</label>
            {{ form.restaurant_owner }}
        </div>
     {% endcomment %}
       
        <button type="submit" class="btn btn-primary">Create Restaurant</button>
    </form>

</section>

{% endblock%}

FinalProjectKiwiFeeds/project_kiwifeeds/templates/app_restaurants/delete_restaurant.html
<!-- TODO User can only access page if they are owner of Resturant -->
{% extends 'base/base.html' %}
{% block content %}
<section>
    <main>
        <form method="POST">
            {% csrf_token %}
            <p>Are you sure you want to delete this restaurant?</p>
            <div class="2btn-wrap">
                <button class="btn btn-action" type="submit">Delete</button>
                {% comment %} <button class="btn btn-dark" type="submit">Cancel</button> {% endcomment %}
                <a href="/restaurants/" class="btn btn-dark" type="submit">Cancel</a>
            </div>
        </form>
    </main>
</section>
{% endblock%}

FinalProjectKiwiFeeds/project_kiwifeeds/templates/app_restaurants/edit_restaurant.html
<!-- TODO User can only access page if they are owner of Resturant -->

{% extends 'base/base.html' %}
{% block content %}
<section>
  <div class='col-wrap'>
    <div class='col-50'>
      <h2>Edit Restaurant</h2>
      <form method="post">
        {% csrf_token %}
        {{ restaurant_form.as_p }}
        <button class="btn btn-action" type="submit" name="edit_restaurant_form">Save Restaurant</button>
      </form>
      
      {% comment %} <h2>Add Food Item</h2>
      <div class='col-50'>
      <h2>Add Food Item</h2>
      <form method="post">
        {% csrf_token %}
        {{ food_form.as_p }}
        <button type="submit" class="btn btn-action" name="add_food_form">Add Food</button>
      </form>
    </div> {% endcomment %}
{% comment %}       
      <h2>Food Items</h2>
      <ul>
        {% for food_item in restaurant.food_set.all %}
        <div class='col-wrap'>
          <div class="col-20">
            <img class='small-img' src="{{ food_item.food_picture.url}}">
          </div>
          <div class='col-80'>
            <h3>
              {{ food_item.name }}
            </h3>
            <p class='item-price'>
              NZD${{ food_item.food_price }}
            </p>
            <p>
              {{ food_item.description }}
            </p>
            <a href="{% url 'edit-food' food_id=food_item.id  %}" class='btn btn-dark'>Edit</a>
            <a href="{% url 'delete-food' food_id=food_item.id  %}" class='btn btn-action'>Delete {{food_item.name}}</a>
          </div>
        </div>
        {% empty %}
          <li>No food items added yet.</li>
        {% endfor %}
      </ul> {% endcomment %}
 

    {% comment %} <hr>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-action" type="submit">Update Restaraunt Details</button>
    </form> {% endcomment %}
</section>
{% endblock%}

FinalProjectKiwiFeeds/project_kiwifeeds/templates/app_restaurants/restaurant_details.html
<!-- TODO: Will need to display Menu Items and Reviews attached to Model on this Page 
Display button to edit and delete if the Resturant is owned by current user
If a user is Logged in and ISNT the resturant owner a button to ass a review should be shown-->


{% extends 'base/base.html' %}
{% load static%}

{% load custom_tags %}
{% block content %}
 
<section>
    <h1 class="r-title">{{restaurant.restaurant_name}}</h1>
    <div class="info-wrap-details">
        <div class="res-details-wrap">
            <div class="icon-text-wrap">
                <img class="icon" src="{% static 'images/icons/location-pin.png' %}">
                <a class="r-info-text">{{restaurant.restaurant_location}}</a>
            </div>
            <div class="icon-text-wrap">
                {% if reviews %}
                <!-- Overall ratign-->
                    <div class="rating-wrap">
                        {% for _ in "x"|ljust:overall_rating %}
                            <img class="icon" src="{% static 'images/icons/star.png' %}">
                        {% endfor %}
                    </div>
                {% endif %}

            </div>
            <div class="icon-text-wrap">
                <img class="icon" src="{% static 'images/icons/owner.png' %}">
                <a class="r-info-text">{{restaurant.restaurant_owner}}</a>
            </div>
        </div>
    </div>
    <p class="text">{{restaurant.restaurant_description}}</p>
    </p>
    <div class="button-wrap">
        <a href="https://www.google.com/maps/place/{{restaurant.restaurant_location}}" target="_blank"class="btn btn-dark">Get Directions</a>
        {% comment %} <a href=""class="btn btn-dark">View Menu</a> {% endcomment %}
        {% if user.is_authenticated and user|user_belongs_to_group:'RestaurantOwner' %}
            {% if restaurant.restaurant_owner == user.userprofile %}
                <a class="btn btn-action" href="{% url 'edit-restaurant' restaurant.id %}" >Edit</a>
            {% endif %}
        {% endif %}
    </div>
    {% if user.is_authenticated and user|user_belongs_to_group:'Customer' %}
            {% if not restaurant.restaurant_owner == user.userprofile %}
                {% if is_favorite %}
                    <form method="post" action="{% url 'remove-from-favorites' restaurant.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-action">Remove from Favorites</button>
                    </form>
                    
                {% else %}
                    <form method="post" action="{% url 'add-to-favorites' %}">
                        {% csrf_token %}
                        <input type="hidden" name="restaurant_id" value="{{ restaurant.id }}">
                        <button type="submit" class="btn btn-action">Add to Favorites</button>
                    </form>
                {% endif %}
            {% endif %}
    
    {% else %}
        {%  if user|user_belongs_to_group:'Admin' %}
            {% comment %} <p> logged in user is Admin, not allowed to add favorite resturant </P> {% endcomment %}
        {% endif %}
        {%  if user|user_belongs_to_group:'RestaurantOwner' %}
            {% comment %} <p> logged in user is resturant onwer, not allowed to add favorite resturant </P> {% endcomment %}
        {% endif %}
        
    {% endif %}
    
</section>
<!-- Food Menu Section-->
<section>
    <h2>{{restaurant.restaurant_name}} Menu</h2>
    {%  if user|user_belongs_to_group:'RestaurantOwner' and restaurant.restaurant_owner == user.userprofile  %}
    <a class='btn btn-action' href="{% url 'add-food' restaurant_id=restaurant.id %}" >Add Food to Menu</a>
    {% endif %}

    <ul>
      {% for food_item in foods %}
      <br>
      {% comment %} {{food_item.food_picture.url}} {% endcomment %}
      <div class='col-wrap'>
        <div class='col-20'>
            <img class="small-img" src="{{food_item.food_picture.url}}">
        </div>
        <div class='col-80'>
            Rest ID:{{food_item.restaurant.id }}
            Food ID:{{food_item.id}}
              <h3>{{ food_item.name }}</h3>
              <p class="item-price">NZD${{ food_item.food_price }}</p>
              <p>{{ food_item.description }} </p>
              {% comment %} resturant owner : {{food.restaurant.restaurant_owner.userprofile}}
              Logged in User :{{restaurant.restaurant_owner}} =={{user.userprofile}} {% endcomment %}
              {%  if user|user_belongs_to_group:'RestaurantOwner' and restaurant.restaurant_owner == user.userprofile %}
                <a class='btn btn-dark' href="{% url 'edit-food' food_id=food_item.id %}">Edit</a>
                <a class='btn btn-action' href="{% url 'delete-food' food_id=food_item.id  %}">Delete {{food_item.name}}</a>
              {% endif %}
        </div>
    </div>
      {% empty %}
        <li>No food items added yet.</li>
      {% endfor %}
    </ul>
</section>

<section>
    <h2>Reviews</h2>
    
    <ul>
     
        {% for review in reviews %}
            <ul>
                <div class="reviews-wrap">
                    <li>
                        <h3 class="rev-name">{{ review.user.this_user.username|title }}</h3>
                        <div class="rating-wrap">
                            {% for _ in "x"|ljust:review.rating %}
                                <img class="icon" src="{% static 'images/icons/star.png' %}">
                            {% endfor %}
                            {% comment %} <a class="r-info-text">{{ review.rating }}</a> {% endcomment %}
                        </div>
                        <p class="review-text text">{{ review.comment }}</p>
                    </li>
                </div>
            </ul>
        {% empty %}
            <p>No reviews available for this restaurant.</p>
        {% endfor %}
    </ul>
    <!--Add review-->
    {%  if user|user_belongs_to_group:'Customer' %}
    <div>
            {% comment %} <form method="post" action="{% url 'write-a-review' restaurant_id=restaurant.id%}">
                {% csrf_token %}
                {{ form.as_p }}  {# Use form.as_p to render form fields #}
                <button type="submit" class="btn btn-primary">write-a-review</button>
            </form> {% endcomment %}
            <a class='btn btn-action' href="{% url 'write-a-review' restaurant_id=restaurant.id %}">add review</a>  
        
    </div>
    {% endif %}
</section>



{% endblock %}

FinalProjectKiwiFeeds/project_kiwifeeds/templates/app_restaurants/restaurant_list.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<section>
    <h1>All Restaraunts</h1>

    {% with restaurant_list=restaurant_list %}
            {% include 'components/restaurant_list_card.html' %}
    {% endwith %}

    <section>
        <div>
            <div class='bottom-cta' id="login-cta">
                <h2 class='cta-heading'>Join the Kiwi Feeds Family</h2>
                <p class='cta-par'>Get ready to embark on a culinary journey like never before. Sign up today to start discovering the flavours of your city, one bite at a time.</p>
                <div class='cta-small-col'>
                    <a href='user/signup-business' class='btn btn-white btn-cta'>Create Business Profile</a>
                </div>
            </div>
        </div>
    
    </section>


</section>

{%endblock content%}